Controllers/ChartController.cs
using System.Web.Mvc;
using MeteorologyStationApp.Models;

namespace MeteorologyStationApp.Controllers
{
    public class ChartController : Controller
    {
        // GET: Chart
        public ActionResult Index()
        {
            ViewBag.Message = "Wykresy danych pogodowych.";
            return View();
        }

        [HttpPost]
        public ActionResult Index(string DaysNumberForTemperatureChart, string TemperatureChartsType, string DaysNumberForHumidityChart, string HumidityChartsType, string PressureChartsType, string DaysNumberForPressureChart)
        {
            ViewBag.Message = "Wykresy danych pogodowych.";
            ViewBag.TemperatureDaysNumber = DaysNumberForTemperatureChart;
            ViewBag.TemperatureType = TemperatureChartsType;
            ViewBag.HumidityDaysNumber = DaysNumberForHumidityChart;
            ViewBag.HumidityType = HumidityChartsType;
            ViewBag.PressureType = PressureChartsType;
            ViewBag.PressureDaysNumber = DaysNumberForPressureChart;
            return View("Charts");
        }

        public ActionResult GenerateTemperatureChart(int daysNumber, string type)
        {

            var chart = new GenerateSpecifiedChartType();
            return File(chart.Chart(GenerateSpecifiedChartType.ChartName.Temperature, type, daysNumber), "img/png");
        }

        public ActionResult GenerateHumidityChart(int daysNumber, string type)
        {
            var chart = new GenerateSpecifiedChartType();
            return File(chart.Chart(GenerateSpecifiedChartType.ChartName.Humidity, type, daysNumber), "img/png");
        }

        public ActionResult GeneratePressureChart(int daysNumber, string type)
        {
            var chart = new GenerateSpecifiedChartType();
            return File(chart.Chart(GenerateSpecifiedChartType.ChartName.Pressure, type, daysNumber), "img/png");
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MeteorologyStationApp.Models;

namespace MeteorologyStationApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult WeatherForecast()
        {
            var predict = new PredictionWheather();
            string[] weatherForecast =  predict.Prediction();

            ViewBag.Message = "Prognoza pogody";
            ViewBag.Opinion = weatherForecast[3];
            ViewBag.Pressure = weatherForecast[0];
            ViewBag.Humidity = weatherForecast[1];
            ViewBag.Temperature = weatherForecast[2];

            return View();
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Strona projektu Stacji Meteorologicznej";
}

<div class="jumbotron">
    <h1><i>MeteoStation</i></h1>
    <p class="lead">Podgląd danych pogodowych z własnej stacjonarnej stacji pogodowej wraz z bazą wiedzy pozwalającą określić warunki pogodowe.</p>
</div>

<div class="container">
    <h3>Opis projektu</h3>
    <p style="text-align: justify;">
        Projekt MeteoStation zawiera w sobie projekt prostej stacji meteo, która zbiera pomiary temperatury, wilgotności oraz ciśnienia atmosferycznego za pomocą zamontowanych czujników. Stacją steruje mikrokontroler na platformie Arduino, który ma za zadanie zbierać wymienione pomiary oraz przekazywać je za pomocą modułu WiFi do bazy danych w okreslonym interwale czasowym (tutaj co jedną godzinę). Aby przeprowadzić konfigurację stacji wykorzstano komunikacje po Bluetooth.
    </p>
    <p style="text-align: justify;">
        Projekt zawiera także aplikacje internetową, dzięki której można przeglądać zgormadzone dane pogodowe ze stacji za pomocą personalizownych wykresów. Użytkownik określa jaki typ wykresu chce zobaczyć oraz ile dni wstecz (od dnia aktualnego) mają zostać pobrane i wyświetlone dane.
        <br/>
        Aplikacja zawiera bazę wiedzy, za pomocą której można zobaczyć prognozę warunków pogodowych w pobliżu stacji meteo oraz określić, czy przebywanie w tym czasie w miejscu w pobliżu stacji jest bezpieczne (np. stacja zamontowana na elektrowni wiatrowej zbiera pomiary warunków na jej szczycie co pozwala ekipie dokonującej przeglądów oraz napraw na określenie czy wejście na maszt elektorwni jest bezpieczny).
    </p>
</div>

<div class="col">
    <div class="col-md-5 table-bordered">
        <h2>Dane pogodowe</h2>
        <p>Wykresy danych pogodowych zebranych przez stację meteorologiczną do dziesięciu dni wstecz!</p>
        <p> @Html.ActionLink("Przejdź", "Index", "Chart", new { area = "" }, new { @class="btn btn-default"}) </p>
    </div>
    <div class="col-md-2"></div>
    <div class="col-md-5 table-bordered">
        <h2>Prognoza</h2>
        <p>Wykorzystanie bazy wiedzy do prognozy warunków pogodowych w pobliżu stacji i informacji o nich.</p>
        <p> @Html.ActionLink("Przejdź", "WeatherForecast", "Home", new { area = "" }, new { @class = "btn btn-default" }) </p>
    </div>
</div>

Views/Home/WeatherForecast.cshtml
@{
    ViewBag.Title = "WeatherForecast";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="jumbotron">
    <h2><i>@ViewBag.Message</i></h2>
    <p style="text-align: justify;" class="lead">
        Predykcja pogody wykorzystująca pomiary z ostatniego czasu dla przewidywania warunków pogodowych na najbliższe kilka godzin w pobliżu pozycji stacji meteorologicznej. Zawiera także opinię o warunkach i zalecane zachowanie w poblizu stacji meteo.
    </p>
</div>
<div class="row" style="text-align: justify;">
    <div class="col-md-4">
        <h3>Prognoza warunków pogodowych</h3>
        <br/>
        <p style="text-align: justify;">
            @ViewBag.Pressure <br/>
            @ViewBag.Humidity <br />
            @ViewBag.Temperature <br />
        </p>
    </div>
    <div class="col-md-2"></div>
    <div class="col-md-4">
        <h3>Opinia o warunkach</h3>
        <br/>
        <p style="text-align: justify;">@ViewBag.Opinion</p>
    </div>
</div>